#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['build', 'build._compat']

package_data = \
{'': ['*']}

package_dir = \
{'': 'src'}

install_requires = \
['packaging >= 24.0', 'pyproject_hooks']

extras_require = \
{':os_name == "nt"': ['colorama'],
 ':python_version < "3.10"': ['importlib-metadata >= 4.6'],
 ':python_version < "3.11"': ['tomli >= 1.1.0'],
 'keyring': ['keyring'],
 'uv': ['uv >= 0.1.18'],
 "virtualenv:python_version < '3.10'": ['virtualenv >= 20.11'],
 "virtualenv:python_version >= '3.10' and python_version < '3.14'": ['virtualenv '
                                                                     '>= '
                                                                     '20.17'],
 "virtualenv:python_version >= '3.14'": ['virtualenv >= 20.31']}

entry_points = \
{'console_scripts': ['pyproject-build = build.__main__:entrypoint'],
 'pipx.run': ['build = build.__main__:entrypoint']}

setup(name='build',
      version='1.4.4',
      description='A simple, correct Python build frontend',
      author=None,
      author_email='Filipe Laíns <lains@riseup.net>, Bernát Gábor <gaborjbernat@gmail.com>, layday <layday@protonmail.com>, Henry Schreiner <henryschreineriii@gmail.com>',
      url=None,
      packages=packages,
      package_data=package_data,
      package_dir=package_dir,
      install_requires=install_requires,
      extras_require=extras_require,
      entry_points=entry_points,
      python_requires='>= 3.9',
     )
